SELECT VEICULO.NOME,VEICULO.PLACA,CATEGORIA.NOME AS CATEGORIA FROM VEICULO
INNER JOIN CATEGORIA
ON (CATEGORIA.ID = VEICULO.ID_CATEGORIA)


SELECT VEICULO.NOME,FINANCIAMENTO.VALOR_PARCELA,FINANCIAMENTO.PARCELAS_TOTAIS,FINANCIAMENTO.PARCELAS_PAGAS FROM VEICULO
INNER JOIN FINANCIAMENTO	
ON (FINANCIAMENTO.ID_VEICULO = VEICULO.ID)


SELECT VEICULO.NOME,MODELO.MODELO,MODELO.MARCA,FINANCIAMENTO.VALOR_PARCELA,FINANCIAMENTO.PARCELAS_TOTAIS,FINANCIAMENTO.PARCELAS_PAGAS 
FROM VEICULO
INNER JOIN FINANCIAMENTO	
ON (FINANCIAMENTO.ID_VEICULO = VEICULO.ID)
INNER JOIN MODELO
ON (MODELO.ID = VEICULO.ID_MODELO)


SELECT VEICULO.NOME,FUNCIONARIO.NOME,MOTORISTA.CNH
FROM VEICULO
INNER JOIN MOTORISTA	
ON (MOTORISTA.ID = VEICULO.ID_MOTORISTA)
INNER JOIN FUNCIONARIO
ON (MOTORISTA.ID_FUNCIONARIO = FUNCIONARIO.ID)


SELECT CLIENTE.NOME,CONTATO.TELEFONE_01,CONTATO.EMAIL FROM CONTATO_CLIENTE AS CC
INNER JOIN CONTATO ON (CC.ID_CONTATO = CONTATO.ID)
INNER JOIN CLIENTE ON (CC.ID_CLIENTE = CLIENTE.ID)


SELECT CLIENTE.NOME,SERVICO.STATUS,FUNCIONARIO.NOME,SERVICO.VALOR_CONTRATO,SERVICO.DATA_INICIO,SERVICO.DATA_FIM FROM SERVICO
INNER JOIN FUNCIONARIO ON (SERVICO.ID_FUNCIONARIO = FUNCIONARIO.ID)
INNER JOIN CLIENTE ON (SERVICO.ID_CLIENTE = CLIENTE.ID)


SELECT VEICULO.NOME,VALOR_PARCELA,PARCELAS_PAGAS,PARCELAS_TOTAIS,FINANCIADOR FROM FINANCIAMENTO
INNER JOIN VEICULO ON (FINANCIAMENTO.ID_VEICULO = VEICULO.ID)
