SELECT * FROM ENDERECO WHERE ENDERECO LIKE 'Avenida%';

SELECT * FROM CONTATO WHERE CONTATO LIKE '%@gmail.com';

SELECT * FROM PESSOA WHERE NOME ILIKE 'ryan augusto da mata';

SELECT * FROM PESSOA_JURIDICA WHERE CNPJ LIKE '03.845.897/0001-42';

SELECT * FROM PESSOA_FISICA WHERE CPF LIKE '240.211.364-28';

SELECT ENDERECO, SIGLA FROM ENDERECO
INNER JOIN ESTADO
ON (ENDERECO.ID_ESTADO = ESTADO.ID)
WHERE SIGLA LIKE 'ES';

SELECT NOME, TRANSPORTE.ID FROM TRANSPORTE
INNER JOIN PESSOA
ON (TRANSPORTE.ID_CLIENTE = PESSOA.ID)
WHERE NOME ILIKE 'DAVI%';

SELECT PESSOA.NOME, AGE(CURRENT_DATE, PESSOA_FISICA.DATA_NASCIMENTO) AS IDADE FROM PESSOA_FISICA
INNER JOIN PESSOA
ON (PESSOA_FISICA.ID_PESSOA = PESSOA.ID);

SELECT NOME, EXTRACT('DAY' FROM (NOW() - DATA_CADASTRO)) AS DIAS_CADASTRADO FROM PESSOA;
								 
SELECT NUMERO_CNH, DATE_PART('DAY', (DATA_VENCIMENTO - NOW())) AS DIAS_VENCIMENTO_CNH FROM MOTORISTA;

SELECT ID, AGE(DATA_FIM, DATA_INICIO) AS TEMPO_TRANSPORTE FROM TRANSPORTE;
									 
SELECT DATA_INICIO, DATA_FIM, AGE(DATA_FIM, DATA_INICIO) AS TEMPO_MOTORISTA_VEICULO FROM MOTORISTA_VEICULO;		
									 
