SELECT TRANSPORTE.ID, VEICULO.NOME, STATUS_TRANSPORTE.STATUS, TRANSP2.VALOR_CONTRATO FROM TRANSPORTE
INNER JOIN VEICULO
ON (TRANSPORTE.ID_VEICULO = VEICULO.ID)
INNER JOIN STATUS_TRANSPORTE
ON(TRANSPORTE.ID_STATUS = STATUS_TRANSPORTE.ID)
INNER JOIN TRANSPORTE AS TRANSP2
ON (TRANSPORTE.ID = TRANSP2.ID);

CREATE VIEW INFORMACAO_MOTORISTAS AS (
	SELECT PESSOA.NOME, NUMERO_CNH, CATEGORIA_CNH.CATEGORIA, DATA_VENCIMENTO FROM MOTORISTA
	INNER JOIN FUNCIONARIO
	ON (MOTORISTA.ID_FUNCIONARIO = FUNCIONARIO.ID)
	INNER JOIN PESSOA_FISICA
	ON (FUNCIONARIO.ID_PESSOA_FISICA = PESSOA_FISICA.ID)
	INNER JOIN PESSOA
	ON (PESSOA_FISICA.ID_PESSOA = PESSOA.ID)
	INNER JOIN CATEGORIA_CNH
	ON (MOTORISTA.ID_CATEGORIA_CNH = CATEGORIA_CNH.ID)
);

CREATE VIEW VEICULOS_INDISPONIVEIS AS (
	SELECT VEICULO.NOME, STATUS_VEICULO.STATUS FROM VEICULO
	INNER JOIN STATUS_VEICULO
	ON (VEICULO.ID_STATUS = STATUS_VEICULO.ID)
	WHERE STATUS != 'DISPONIVEL'
);

CREATE VIEW CLIENTE_TRANSPORTE AS (
	SELECT TRANSPORTE.ID AS ID_TRANSPORTE, PESSOA.NOME, TRANSPORTE.VALOR_CONTRATO, TRANSPORTE.DATA_INICIO, TRANSPORTE.DATA_FIM FROM TRANSPORTE
	INNER JOIN PESSOA
	ON (TRANSPORTE.ID_CLIENTE = PESSOA.ID)
);

CREATE VIEW TRANSPORTES_CONCLUIDOS AS (
	SELECT TRANSPORTE.ID, PESSOA.NOME, STATUS_TRANSPORTE.STATUS FROM TRANSPORTE
	INNER JOIN PESSOA
	ON (TRANSPORTE.ID_CLIENTE = PESSOA.ID)
	INNER JOIN STATUS_TRANSPORTE
	ON (TRANSPORTE.ID_STATUS = STATUS_TRANSPORTE.ID)
	WHERE STATUS = 'CONCLUIDO'
);

CREATE VIEW VEICULOS_DISPONIVEIS AS (
	SELECT VEICULO.NOME, STATUS_VEICULO.STATUS FROM VEICULO
	INNER JOIN STATUS_VEICULO
	ON (VEICULO.ID_STATUS = STATUS_VEICULO.ID)
	WHERE STATUS = 'DISPONIVEL'
);

