SELECT VEICULO.NOME,VEICULO.PLACA,CATEGORIA.NOME AS CATEGORIA FROM VEICULO
INNER JOIN CATEGORIA
ON (CATEGORIA.ID = VEICULO.ID_CATEGORIA)


SELECT VEICULO.NOME,FINANCIAMENTO.VALOR_PARCELA,FINANCIAMENTO.PARCELAS_TOTAIS,FINANCIAMENTO.PARCELAS_PAGAS FROM VEICULO
INNER JOIN FINANCIAMENTO	
ON (FINANCIAMENTO.ID_VEICULO = VEICULO.ID)


SELECT VEICULO.NOME,MODELO.MODELO,MODELO.MARCA,FINANCIAMENTO.VALOR_PARCELA,FINANCIAMENTO.PARCELAS_TOTAIS,FINANCIAMENTO.PARCELAS_PAGAS 
FROM VEICULO
INNER JOIN FINANCIAMENTO	
ON (FINANCIAMENTO.ID_VEICULO = VEICULO.ID)
INNER JOIN MODELO
ON (MODELO.ID = VEICULO.ID_MODELO)


SELECT VEICULO.NOME,FUNCIONARIO.NOME,MOTORISTA.CNH
FROM VEICULO
INNER JOIN MOTORISTA	
ON (MOTORISTA.ID = VEICULO.ID_MOTORISTA)
INNER JOIN FUNCIONARIO
ON (MOTORISTA.ID_FUNCIONARIO = FUNCIONARIO.ID)
