SELECT STATUS_TRANSPORTE.STATUS, COUNT(STATUS_TRANSPORTE.STATUS) AS QNT_STATUS_TRANSPORTE FROM TRANSPORTE
INNER JOIN STATUS_TRANSPORTE
ON (TRANSPORTE.ID_STATUS = STATUS_TRANSPORTE.ID)
GROUP BY STATUS_TRANSPORTE.STATUS;

SELECT TIPO_CARGA.TIPO, SUM(VALOR_CONTRATO) AS VALOR_TOTAL_TIPO_TRANSPORTE FROM TRANSPORTE
INNER JOIN TIPO_CARGA
ON (TRANSPORTE.ID_TIPO_CARGA = TIPO_CARGA.ID)
GROUP BY TIPO_CARGA.TIPO
ORDER BY VALOR_TOTAL_TIPO_TRANSPORTE DESC;

SELECT PESSOA.NOME, SUM(FUNCIONARIO.SALARIO) AS SALARIO_FUNCIONARIO FROM FUNCIONARIO
INNER JOIN PESSOA_FISICA
ON (FUNCIONARIO.ID_PESSOA_FISICA = PESSOA_FISICA.ID)
INNER JOIN PESSOA
ON (PESSOA_FISICA.ID_PESSOA = PESSOA.ID)
GROUP BY PESSOA.NOME
HAVING SUM(FUNCIONARIO.SALARIO) > 3300
ORDER BY SALARIO_FUNCIONARIO DESC;

SELECT SUM(VALOR_CONTRATO) AS FATURAMENTO_TRANSPORTE FROM TRANSPORTE;

SELECT PESSOA.NOME, COUNT(PESSOA.NOME) AS NUMERO_DE_CONTRATOS FROM TRANSPORTE
INNER JOIN PESSOA
ON (TRANSPORTE.ID_CLIENTE = PESSOA.ID)
GROUP BY PESSOA.NOME
ORDER BY COUNT(PESSOA.NOME) DESC;

SELECT STATUS_VEICULO.STATUS, COUNT(STATUS_VEICULO.STATUS) AS QNT_STATUS FROM VEICULO
INNER JOIN STATUS_VEICULO
ON (VEICULO.ID_STATUS = STATUS_VEICULO.ID)
GROUP BY STATUS_VEICULO.STATUS;

