CREATE TABLE CLIENTE (
  ID INT AUTO_INCREMENT NOT NULL,
  NOME VARCHAR(45),
  TIPO_CLIENTE CHAR(1),
  CNPJ VARCHAR(18),
  CPF VARCHAR(14),
  DATA_CADASTRO DATE,
  DATA_NASCIMENTO DATE,
  PRIMARY KEY (ID)
);

CREATE TABLE FUNCIONARIO (
  ID INT AUTO_INCREMENT NOT NULL,
  NOME VARCHAR(45),
  CPF VARCHAR(14),
  CARGO VARCHAR(30),
  SALARIO FLOAT,
  SEXO CHAR(1),
  DATA_CADASTRO DATE,
  DATA_NASCIMENTO DATE,
  PRIMARY KEY (ID)
);


CREATE TABLE MOTORISTA (
  ID INT AUTO_INCREMENT NOT NULL,
  CNH VARCHAR(11),
  DATA_VENCIMENTO DATE,
  TIPO VARCHAR(2),
  ID_FUNCIONARIO INT NOT NULL,
  PRIMARY KEY (ID),
	CONSTRAINT fk_motorista
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIO (ID)
);


CREATE TABLE CONTATO (
  ID INT AUTO_INCREMENT NOT NULL,
  TELEFONE_01 VARCHAR(12),
  TELEFONE_02 VARCHAR(12),
  TELEFONE_03 VARCHAR(12),
  EMAIL VARCHAR(45),
  PRIMARY KEY (ID)
);

CREATE TABLE ENDERECO (
  ID INT AUTO_INCREMENT NOT NULL,
  ENDERECO VARCHAR(45),
  LOGADOURO VARCHAR(20),
  NUMERO INT,
  CEP VARCHAR(9),
  COMPLEMENTO VARCHAR(20),
  CIDADE VARCHAR(35),
  ESTADO VARCHAR(20),
  PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA (
  ID INT NOT NULL,
  NOME VARCHAR(45),
  PRIMARY KEY (ID)
);


CREATE TABLE MODELO (
  ID INT AUTO_INCREMENT NOT NULL,
  MODELO VARCHAR(45),
  MARCA VARCHAR(20),
  ANO VARCHAR(4),
  EIXO INT,
  PESO FLOAT,
  ALTURA FLOAT,
  LARGURA FLOAT,
  COMPRIMENTO FLOAT,
  COR VARCHAR(20),
  PRIMARY KEY (ID)
);

CREATE TABLE VEICULO (
  ID INT AUTO_INCREMENT NOT NULL,
  NOME VARCHAR(45),
  CHASSI VARCHAR(45),
  PLACA VARCHAR(7),
  STATUS VARCHAR(20),
  COMBUSTIVEL VARCHAR(15),
  ID_CATEGORIA INT NOT NULL,
  ID_MODELO INT NOT NULL,
  ID_MOTORISTA INT NOT NULL,
  PRIMARY KEY (ID),
	CONSTRAINT fk_veiculo1
    FOREIGN KEY (ID_CATEGORIA)
    REFERENCES CATEGORIA (ID),
	CONSTRAINT fk_veiculo2
    FOREIGN KEY (ID_MODELO)
    REFERENCES MODELO (ID),
	CONSTRAINT fk_veiculo3
    FOREIGN KEY (ID_MOTORISTA)
    REFERENCES MOTORISTA (ID)
);

CREATE TABLE SEGURO (
  ID INT AUTO_INCREMENT NOT NULL,
  STATUS VARCHAR(20),
  DATA_VENCIMENTO DATE,
  FIM_CONTRATO DATE,
  ID_VEICULO INT NOT NULL,
  PRIMARY KEY (ID),
	CONSTRAINT fk_seguro
    FOREIGN KEY (ID_VEICULO)
    REFERENCES VEICULO (ID)
);


CREATE TABLE FINANCIAMENTO (
  ID INT AUTO_INCREMENT NOT NULL,
  VALOR_PARCELA FLOAT,
  PARELAS_TOTAIS INT,
  PARCELAS_PAGAS INT,
  FIANCIADOR INT,
  ID_VEICULO INT NOT NULL,
  PRIMARY KEY (ID),
  	CONSTRAINT fk_fianciamento
    FOREIGN KEY (ID_VEICULO)
    REFERENCES VEICULO (ID)
);


CREATE TABLE ENDERECO_SERVICO (
  ID INT AUTO_INCREMENT NOT NULL,
  TIPO CHAR,
  ID_ENDERECO INT NOT NULL,
  PRIMARY KEY (ID),
  	CONSTRAINT fk_endereco_servico
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES ENDERECO (ID)
);

CREATE TABLE SERVICO (
  ID INT AUTO_INCREMENT NOT NULL,
  STATUS VARCHAR(15),
  VALOR_CONTRATO FLOAT,
  DATA_INICIO DATE,
  DATA_FIM DATE,
  ID_CLIENTE INT NOT NULL,
  ID_FUNCIONARIO INT NOT NULL,
  ID_VEICULO INT NOT NULL,
  ID_ENDERECO_ORIGEM INT NOT NULL,
  ID_ENDERECO_DESTINO INT NOT NULL,
  PRIMARY KEY (ID),
  	CONSTRAINT fk_servico1
    FOREIGN KEY (ID_ENDERECO_ORIGEM)
    REFERENCES ENDERECO_SERVICO (ID),
    CONSTRAINT fk_servico2
    FOREIGN KEY (ID_ENDERECO_DESTINO)
    REFERENCES ENDERECO_SERVICO (ID),
    CONSTRAINT fk_servico3
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID),
    CONSTRAINT fk_servico4
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIO (ID),
    CONSTRAINT fk_servico5
    FOREIGN KEY (ID_VEICULO)
    REFERENCES VEICULO (ID)
);

CREATE TABLE ENDERECO_CLIENTE (
  ID INT AUTO_INCREMENT NOT NULL,
  ID_CLIENTE INT NOT NULL,
  ID_ENDERECO INT NOT NULL,
  PRIMARY KEY (ID),
	CONSTRAINT fk_endereco_cliente1
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID),
    CONSTRAINT fk_endereco_cliente2
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES ENDERECO (ID)
);

CREATE TABLE ENDERECO_FUNCIONARIO (
  ID INT AUTO_INCREMENT NOT NULL,
  ID_FUNCIONARIO INT NOT NULL,
  ID_ENDERECO INT NOT NULL,
  PRIMARY KEY (ID),
	CONSTRAINT fk_endereco_funcionario1
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIO (ID),
    CONSTRAINT fk_endereco_funcionario2
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES ENDERECO (ID)
);

CREATE TABLE CONTATO_FUNCIONARIO (
  ID INT AUTO_INCREMENT NOT NULL,
  ID_CONTATO INT NOT NULL,
  ID_FUNCIONARIO INT NOT NULL,
  PRIMARY KEY (ID),
	CONSTRAINT fk_contato_funcionario1
    FOREIGN KEY (ID_CONTATO)
    REFERENCES CONTATO (ID),
    CONSTRAINT fk_contato_funcionario2
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIO (ID)
);

CREATE TABLE CONTATO_CLIENTE (
  ID INT AUTO_INCREMENT NOT NULL,
  ID_CONTATO INT NOT NULL,
  ID_CLIENTE INT NOT NULL,
  PRIMARY KEY (ID),
	CONSTRAINT fk_contato_cliente1
    FOREIGN KEY (ID_CONTATO)
    REFERENCES CONTATO (ID),
    CONSTRAINT fk_contato_cliente2
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID)
);
