DROP TABLE IF EXISTS ENDERECO_CLIENTE;

DROP TABLE IF EXISTS CONTATO_CLIENTE;

DROP TABLE IF EXISTS ENDERECO_FUNCIONARIO;

DROP TABLE IF EXISTS CONTATO_FUNCIONARIO;

DROP TABLE IF EXISTS FINANCIAMENTO;

DROP TABLE IF EXISTS SERVICO;

DROP TABLE IF EXISTS ENDERECO_SERVICO;

DROP TABLE IF EXISTS SEGURO;

DROP TABLE IF EXISTS VEICULO ;

DROP TABLE IF EXISTS MOTORISTA;

DROP TABLE IF EXISTS CLIENTE;

DROP TABLE IF EXISTS FUNCIONARIO;

DROP TABLE IF EXISTS CONTATO;

DROP TABLE IF EXISTS ENDERECO;

DROP TABLE IF EXISTS MODELO;

DROP TABLE IF EXISTS CATEGORIA;
