INSERT INTO TIPO_CONTATO (TIPO) VALUES ('EMAIL'), ('TELEFONE'), ('CELULAR');

INSERT INTO CATEGORIA_CNH (CATEGORIA) VALUES ('A'), ('B'), ('C'), ('D'), ('E');

INSERT INTO CATEGORIA (NOME) VALUES ('A'), ('B'), ('C'), ('D'), ('E');

INSERT INTO EIXO (EIXO) VALUES (2), (4), (6);

INSERT INTO MARCA (MARCA) VALUES ('Mercedes-Benz'), ('Ford'), ('Volkswagen'), ('Volvo'), ('Scania');

INSERT INTO STATUS_VEICULO (STATUS) VALUES ('DISPONIVEL'), ('MANUTENCAO'), ('EM TRANSPORTE');

INSERT INTO STATUS_TRANSPORTE (STATUS) VALUES ('CONCLUIDO'), ('EM ANDAMENTO'), ('CANCELADO'), ('SOLICITADO');

INSERT INTO COMBUSTIVEL (COMBUSTIVEL) VALUES ('GASOLINA'), ('ALCOOL'), ('GAS'), ('FLEX');

INSERT INTO COR (COR) VALUES ('VERMELHO'), ('AZUL'), ('VERDE'), ('PRETO'), ('BRANCO'), ('PRATA'), ('AMARELO'), ('LARANJA'), ('CINZA');

INSERT INTO LOGRADOURO (NOME, ABREVIACAO) VALUES
('ACESSO', 'ACS'),
('ADRO' ,'AD'),
('AEROPORTO', 'AER'),
('ALAMEDA', 'AL'),
('ALTO' ,'AT'),
('AVENIDA', 'AV'),
('BAIRRO', 'B'),
('BECO' ,'BC'),
('BLOCO' ,'BL'),
('CHACARA', 'CH'),
('CIDADE' ,'CD'),
('CONDOMINIO', 'COND'),
('CONJUNTO' ,'CJ'),
('EDIFICIO' ,'ED'),
('ENTREPOSTO', 'ETP'),
('ENTRONCAMENTO', 'ENT'),
('ESTACAO', 'ETC'),
('ESTRADA', 'EST'),
('FAVELA' ,'FAV'),
('FERROVIA', 'FER'),
('JARDIM' ,'JD'),
('MORRO' ,'MRO'),
('PARQUE', 'PQ'),
('PONTE' ,'PTE'),
('POSTO' ,'POS'),
('PRACA' ,'PCA'),
('PRAIA' ,'PR'),
('RETA' ,'RTA'),
('RIO' ,'RIO'),
('RODOVIA' ,'RDV'),
('RUA' ,'R');
