SELECT DISTINCT	
		STATUS_TRANSPORTE.STATUS AS STATUS_TRANSPORTE,
		TIPO_CARGA.TIPO,
		CLIENTE.NOME AS CLIENTE,
		TIPO_CONTATO.TIPO AS TIPO_CONTATO_CLIENTE,
		CONTATO.CONTATO AS CONTATO_CLIENTE,
		FUNCIONARIO_RESPONSAVEL.NOME AS FUNCIONARIO_RESPONSAVEL,
		VEICULO.ID,
		VEICULO.NOME AS VEICULO,
		COMBUSTIVEL.COMBUSTIVEL AS COMBUSTIVEL_VEICULO,
		CATEGORIA_VEICULO.CATEGORIA AS CATEGORIA_VEICULO,
		MARCA.MARCA AS MARCA_VEICULO,
		COR.COR AS COR_VEICULO,
		EIXO.QUANTIDADE_EIXO AS EIXO_VEICULO,
		STATUS_VEICULO.STATUS AS STATUS_VEICULO,
		ORIGEM.ENDERECO AS ORIGEM,
		DESTINO.ENDERECO AS DESTINO,
		LOGRADOURO.ABREVIACAO AS LOGRADOURO_ORIGEM,
		ESTADO.SIGLA AS ESTADO_ORIGEM,
		CIDADE.NOME AS CIDADE_ORIGEM,
		BAIRRO.NOME AS BAIRRO_ORIGEM
FROM TRANSPORTE
INNER JOIN TIPO_CARGA
ON (TRANSPORTE.ID_TIPO_CARGA = TIPO_CARGA.ID)
INNER JOIN STATUS_TRANSPORTE
ON (TRANSPORTE.ID_STATUS = STATUS_TRANSPORTE.ID)
INNER JOIN PESSOA AS CLIENTE
ON (TRANSPORTE.ID_CLIENTE = CLIENTE.ID)
INNER JOIN FUNCIONARIO
ON (TRANSPORTE.ID_FUNCIONARIO = FUNCIONARIO.ID)
INNER JOIN PESSOA_FISICA
ON (FUNCIONARIO.ID_PESSOA_FISICA = PESSOA_FISICA.ID)
INNER JOIN PESSOA AS FUNCIONARIO_RESPONSAVEL
ON (PESSOA_FISICA.ID = FUNCIONARIO_RESPONSAVEL.ID)
INNER JOIN VEICULO
ON (TRANSPORTE.ID_VEICULO = VEICULO.ID)
INNER JOIN ENDERECO AS ORIGEM
ON (TRANSPORTE.ID_ENDERECO_ORIGEM = ORIGEM.ID)
INNER JOIN ENDERECO AS DESTINO
ON (TRANSPORTE.ID_ENDERECO_DESTINO = DESTINO.ID)
INNER JOIN LOGRADOURO
ON (ORIGEM.ID_LOGRADOURO = LOGRADOURO.ID)
INNER JOIN ESTADO
ON (ORIGEM.ID_ESTADO = ESTADO.ID)
INNER JOIN CIDADE
ON (ESTADO.ID = CIDADE.ID_ESTADO)
INNER JOIN BAIRRO
ON (CIDADE.ID = BAIRRO.ID_CIDADE)
INNER JOIN CONTATO
ON (CLIENTE.ID = CONTATO.ID_PESSOA)
INNER JOIN TIPO_CONTATO
ON (CONTATO.ID_TIPO = TIPO_CONTATO.ID)
INNER JOIN COMBUSTIVEL
ON (VEICULO.ID_COMBUSTIVEL = COMBUSTIVEL.ID)
INNER JOIN CATEGORIA_VEICULO
ON (VEICULO.ID_CATEGORIA = CATEGORIA_VEICULO.ID)
INNER JOIN STATUS_VEICULO
ON (VEICULO.ID_STATUS = STATUS_VEICULO.ID)
INNER JOIN MODELO 
ON (VEICULO.ID_MODELO = MODELO.ID)
INNER JOIN MARCA
ON (MODELO.ID_MARCA = MARCA.ID)
INNER JOIN EIXO
ON (MODELO.ID_EIXO = EIXO.ID)
INNER JOIN COR
ON (MODELO.ID_COR = COR.ID)
WHERE TIPO_CONTATO.TIPO IN (
	SELECT TIPO FROM TIPO_CONTATO
	WHERE TIPO = 'EMAIL'
);



SELECT STATUS_TRANSPORTE.STATUS, COUNT(STATUS_TRANSPORTE.STATUS) AS QNT_STATUS FROM TRANSPORTE
INNER JOIN STATUS_TRANSPORTE
ON (TRANSPORTE.ID_STATUS = STATUS_TRANSPORTE.ID)
GROUP BY (STATUS_TRANSPORTE.STATUS)
ORDER BY QNT_STATUS;

SELECT MARCA.MARCA, COUNT(MARCA.MARCA) AS QNT_MARCAS_VEICULO FROM VEICULO
INNER JOIN MODELO
ON (VEICULO.ID_MODELO = MODELO.ID)
INNER JOIN MARCA
ON (MODELO.ID_MARCA = MARCA.ID)
GROUP BY (MARCA.MARCA)
ORDER BY (QNT_MARCAS_VEICULO) DESC;

SELECT FUNCIONARIO_NOME.NOME AS FUNCIONARIO_NOME, SALARIO FROM FUNCIONARIO
INNER JOIN PESSOA_FISICA
ON (FUNCIONARIO.ID_PESSOA_FISICA = PESSOA_FISICA.ID)
INNER JOIN PESSOA AS FUNCIONARIO_NOME
ON (PESSOA_FISICA.ID_PESSOA = FUNCIONARIO_NOME.ID)
WHERE CARGO LIKE 'MOTORISTA'
ORDER BY (SALARIO) DESC;

SELECT VEICULO.NOME, STATUS_VEICULO.STATUS FROM VEICULO
INNER JOIN STATUS_VEICULO
ON (VEICULO.ID_STATUS = STATUS_VEICULO.ID)
ORDER BY (STATUS);

SELECT PESSOA.NOME, CONTATO.CONTATO FROM PESSOA
INNER JOIN CONTATO
ON (PESSOA.ID = CONTATO.ID_PESSOA);









