SELECT 	STATUS_TRANSPORTE.STATUS AS STATUS_TRANSPORTE, 
		CLIENTE.NOME AS CLIENTE,
		FUNCIONARIO_RESPONSAVEL.NOME AS FUNCIONARIO_RESPONSAVEL,
		VEICULO.NOME AS VEICULO, 
		ORIGEM.ENDERECO AS ORIGEM,
		DESTINO.ENDERECO AS DESTINO
FROM TRANSPORTE
INNER JOIN STATUS_TRANSPORTE
ON (TRANSPORTE.ID_STATUS = STATUS_TRANSPORTE.ID)
INNER JOIN PESSOA AS CLIENTE
ON (TRANSPORTE.ID_CLIENTE = CLIENTE.ID)
INNER JOIN FUNCIONARIO
ON (TRANSPORTE.ID_FUNCIONARIO = FUNCIONARIO.ID)
INNER JOIN PESSOA_FISICA
ON (FUNCIONARIO.ID_PESSOA_FISICA = PESSOA_FISICA.ID)
INNER JOIN PESSOA AS FUNCIONARIO_RESPONSAVEL
ON (PESSOA_FISICA.ID = FUNCIONARIO_RESPONSAVEL.ID)
INNER JOIN VEICULO
ON (TRANSPORTE.ID_VEICULO = VEICULO.ID)
INNER JOIN ENDERECO AS ORIGEM
ON (TRANSPORTE.ID_ENDERECO_ORIGEM = ORIGEM.ID)
INNER JOIN ENDERECO AS DESTINO
ON (TRANSPORTE.ID_ENDERECO_DESTINO = DESTINO.ID);

SELECT STATUS_TRANSPORTE.STATUS, COUNT(STATUS_TRANSPORTE.STATUS) AS QNT_STATUS FROM TRANSPORTE
INNER JOIN STATUS_TRANSPORTE
ON (TRANSPORTE.ID_STATUS = STATUS_TRANSPORTE.ID)
GROUP BY (STATUS_TRANSPORTE.STATUS)
ORDER BY QNT_STATUS;

SELECT MARCA.MARCA, COUNT(MARCA.MARCA) AS QNT_MARCAS_VEICULO FROM VEICULO
INNER JOIN MODELO
ON (VEICULO.ID_MODELO = MODELO.ID)
INNER JOIN MARCA
ON (MODELO.ID_MARCA = MARCA.ID)
GROUP BY (MARCA.MARCA)
ORDER BY (QNT_MARCAS_VEICULO) DESC;

SELECT FUNCIONARIO_NOME.NOME AS FUNCIONARIO_NOME, SALARIO FROM FUNCIONARIO
INNER JOIN PESSOA_FISICA
ON (FUNCIONARIO.ID_PESSOA_FISICA = PESSOA_FISICA.ID)
INNER JOIN PESSOA AS FUNCIONARIO_NOME
ON (PESSOA_FISICA.ID_PESSOA = FUNCIONARIO_NOME.ID)
WHERE CARGO LIKE 'MOTORISTA'
ORDER BY (SALARIO) DESC;

SELECT VEICULO.NOME, STATUS_VEICULO.STATUS FROM VEICULO
INNER JOIN STATUS_VEICULO
ON (VEICULO.ID_STATUS = STATUS_VEICULO.ID)
ORDER BY (STATUS);

SELECT PESSOA.NOME, CONTATO.CONTATO FROM PESSOA
INNER JOIN CONTATO
ON (PESSOA.ID = CONTATO.ID_PESSOA);









