SELECT * FROM TRANSPORTE WHERE VALOR_CONTRATO > 4000.00 AND VALOR_CONTRATO < 8000.00;

SELECT * FROM FUNCIONARIO WHERE CARGO LIKE 'MOTORISTA' AND SALARIO > 3000.00;

SELECT TRANSPORTE.ID, TIPO_CARGA.TIPO FROM TRANSPORTE
INNER JOIN TIPO_CARGA
ON (TRANSPORTE.ID_TIPO_CARGA = TIPO_CARGA.ID)
WHERE TIPO_CARGA.TIPO LIKE 'CONSTRUCAO' OR TIPO_CARGA.TIPO LIKE 'VEICULO';

SELECT VEICULO.ID, VEICULO.NOME, STATUS_VEICULO.STATUS FROM VEICULO
INNER JOIN STATUS_VEICULO
ON (VEICULO.ID_STATUS = STATUS_VEICULO.ID)
WHERE STATUS LIKE 'MANUTENCAO' OR STATUS LIKE 'EM TRANSPORTE';

SELECT NUMERO_CNH, CATEGORIA FROM MOTORISTA
INNER JOIN CATEGORIA_CNH
ON (ID_CATEGORIA_CNH = CATEGORIA_CNH.ID)
WHERE CATEGORIA LIKE 'AC' OR CATEGORIA LIKE 'AD';

SELECT SUM(VALOR_CONTRATO)/COUNT(ID) AS MEDIA_CONTRATOS FROM TRANSPORTE;

SELECT SUM(SALARIO)/COUNT(ID) AS MEDIA_SALARIO FROM FUNCIONARIO;

SELECT SUM(SALARIO) * 13 AS FOLHA_SALARIAL_ANUAL FROM FUNCIONARIO;

SELECT VEICULO.NOME AS VEICULOS_DISPONIVEIS, STATUS_VEICULO.STATUS FROM VEICULO
INNER JOIN STATUS_VEICULO
ON (VEICULO.ID_STATUS = STATUS_VEICULO.ID)
WHERE STATUS LIKE 'DISPONIVEL';

SELECT VEICULO.NOME AS VEICULO_TIPO_COMBUSTIVEL, COMBUSTIVEL FROM VEICULO
INNER JOIN COMBUSTIVEL
ON (VEICULO.ID_COMBUSTIVEL = COMBUSTIVEL.ID);

SELECT VEICULO.NOME AS VEICULOS_INDISPONIVEIS, STATUS_VEICULO.STATUS FROM VEICULO
INNER JOIN STATUS_VEICULO
ON (VEICULO.ID_STATUS = STATUS_VEICULO.ID)
WHERE STATUS LIKE 'MANUTENCAO' OR STATUS LIKE 'EM TRANSPORTE';



