UPDATE VEICULO SET ID_STATUS = 1 WHERE ID_STATUS = 3;

UPDATE TRANSPORTE SET ID_STATUS = 2 WHERE ID = 4;

UPDATE TRANSPORTE SET ID_VEICULO = 5 WHERE ID = 6;

DELETE FROM CONTATO WHERE ID_PESSOA = 1;

DELETE FROM MOTORISTA_VEICULO WHERE ID_MOTORISTA = 1;

DELETE FROM MOTORISTA WHERE ID_FUNCIONARIO = 1;

DELETE FROM FUNCIONARIO WHERE ID_PESSOA_FISICA = 1;

DELETE FROM PESSOA_FISICA WHERE ID_PESSOA = 1;

DELETE FROM PESSOA WHERE ID = 1;


