SELECT * FROM FUNCIONARIO WHERE CARGO LIKE 'MOTORISTA';

SELECT * FROM FUNCIONARIO WHERE SALARIO > 2500.00;

SELECT * FROM TRANSPORTE WHERE VALOR_CONTRATO > 6000.00;

SELECT * FROM TRANSPORTE WHERE ID_STATUS = 1;